# So, I recognized this as partitions, but I couldn't find any algorithm sufficently fast for my patience...
# According to wikipedia's page on partition, partitions(100) = 190,569,292... so...
# SOLVED : 190569291
